version: '3'

services:
  server:
    image: registry.gitlab.com/commento/commento
    ports:
      - 9090:9090
    environment:
      COMMENTO_ORIGIN: http://localhost:9090
      COMMENTO_PORT: 9090
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

volumes:
  postgres_data_volume:
