EXPOSITIONS:
- optimization
GENERAL:
- odisha
- ml-overview
MATHEMATICS:
- linearAlgebra
POD:
- 1bit-pod
READING:
- reading
RESEARCH:
- research
- proposal
- tensors
- quals
- physicsML
TALKS:
- talks
