FALL2019:
        - MATH505A(3) | Applied Probability | Remigijus Mikulevicius
        - CSCI651(4) | Advanced Computer Networks | Ramesh Govinan
        - CSCI697(1) | Seminar in Computer Science | Leana Golubchik
        - CSCI646(4) [DROPPED] | Coordinated Mobile Robotics | Nora Ayanian
SPRING2020:
        - MATH505B(3) | Applied Probabilty | Remigijus Mikulevicius
        - CSCI567(4) | Machine Learning | Yan Liu
        - THTR101(2) | Improv I | Paul Hungerford
        - CSCI697(1) | Seminar in Computer Science | Leana Golubchik
        - EALC101X(2) | Conversational Chinese and Intercultural Communication | John Chang
SUMMER2020:
        - MATH225(4) | Linear Algebra | Neelesh Tiruviluamala
FALL2020: 
        - EE510(4) | Linear Algebra for Engineers | Benjamin W. Reichardt
        - MATH532(3) | Combinatorial Analysis | Sami H. Assaf
        - MATH499(4) | Special Topics - Consulting Data with Python | Neelesh Tiruviluamala
        - CSCI698(1) | Practicum in Teaching Computer Science | Ellis Horowitz
        - EE250 (Teaching Assistant) | Distributed Systems & the Internet Of Things | Mark Redekopp
SPRING2021:
        - CSCI697(1) | Seminar in Computer Science | Cyrus Shahabi
        - MATH395(2) | Seminar in Problem Solving | Greta Panova
        - CSCI699(4) | Special Topics - Crafting a Research Agenda | Barath Raghavan
        - ISE632(3) | Network Flow and Combinatorial Optimisation | John Gunnar Carlsson
        - EALC103A(2) | Chinese | Christopher Magriney
        - EE250 (Teaching Assistant) | Distributed Systems & the Internet of Things | Bhaskar Krishnamachari
FALL2021:
        - CSCI670(4) | Advanced Analysis of Algorithms | Shang-Hua Teng
        - MATH574(3) | Applied Matrix Analysis | Robert Guralnick
        - MATH425A(4) [Dropped] | Real Analysis | Wojciech Ożański
        - PHED106A | Physical Conditioning | Steve Hsu
        - EE250 (Teaching Assistant) | Distributed Systems & the Internet of Things | Mark Redekopp
SPRING2024:
        - CSCI698(1) | Practicum in Teaching Computer Science | Andrew Goodney     
        - CSCI790(2) | Research | Ferrara Emilio
        - PHED110A(1)| Swimming | Ian Culbertson
        - THTR322(2) | Improv 2: Advanced Improv | Nick Massouh
