FALL2019:
        - MATH505A(3) | Applied Probability | Remigijus Mikulevicius
        - CSCI651(4) | Advanced Computer Networks | Ramesh Govinan
        - CSCI697(1) | Seminar in Computer Science | Leana Golubchik
        - CSCI646(4) [DROPPED] | Coordinated Mobile Robotics | Nora Ayanian
SPRING2020:
        - MATH505B(3) | Applied Probabilty | Remigijus Mikulevicius
        - CSCI567(4) | Machine Learning | Yan Liu
        - THTR101(2) | Improv I | Paul Hungerford
        - CSCI697(1) | Seminar in Computer Science | Leana Golubchik
        - EALC101X | Conversational Chinese and Intercultural Communication | John Chang
SUMMER2020:
        - MATH225 | Linear Algebra | Neelesh Tiruviluamala
FALL2020: 
        - EE510 | Linear Algebra for Engineers | Benjamin W. Reichardt
        - MATH532 | Combinatorial Analysis | Sami H. Assaf
        - MATH499 | Special Topics - Consulting Data with Python | Neelesh Tiruviluamala
        - CSCI698 | Practicum in Teaching Computer Science | Ellis Horowitz
        - EE250 (Teaching Assistant) | Distributed Systems & the Internet Of Things | Mark Redekopp
SPRING2021:
        - CSCI697 | Seminar in Computer Science | Cyrus Shahabi
        - MATH395 | Seminar in Problem Solving | Greta Panova
        - CSCI699 | Special Topics - Crafting a Research Agenda | Barath Raghavan
        - ISE632 | Network Flow and Combinatorial Optimisation | John Gunnar Carlsson
        - EALC103A | Chinese | Christopher Magriney
