EDUCATORS:
        - 'Salman Khan [ Khan Academy ]'
        - 'Prof. Luis von Ahn [ Duolingo ]'
TECHNOLOGISTS:
        - 'Swee Ann Teo [Espressif]' 
ARTISTS:
        - 'Joaquin Phoenix [Method Actor]'
