AI,PROBABILITY:
- csci-360-ai
AOPS:
- AoPS
COURSES:
- csci567-machine-learning
- csci670-advanced-analysis-of-algorithms
- csci675-convex-optimisation
- csci698-practicum-in-teaching-computer-science-sp24
- csci699-computational-perspectives-on-ml
- ee503-probability
- ee546-mathematics-of-high-dimensional-data
- math425A-real-analysis
- math501-summer-2023
- math574-applied-matrix-analysis
- phys438a-quantum-mechanics
GENERAL:
- phy760-computational-methods-in-physics
OPTIMISATION:
- constrained-convex-optimisation
TABLE-TENNIS:
- phed-150A-table-tennis
VIDEORESOURCES:
- videoresources
