COURSES:
- csci670-advanced-analysis-of-algorithms
- csci675-convex-optimisation
- csci699-computational-perspectives-on-ml
- math574-applied-matrix-analysis
- ee546-mathematics-of-high-dimensional-data
- math425A-real-analysis
GENERAL:
- phy760-computational-methods-in-physics
OPTIMISATION:
- constrained-convex-optimisation
TABLE-TENNIS:
- phed-150A-table-tennis
VIDEORESOURCES:
- videoresources
