AOPS:
- AoPS
COURSES:
- csci698-practicum-in-teaching-computer-science-sp24
- math501-summer-2023
- math574-applied-matrix-analysis
- ee546-mathematics-of-high-dimensional-data
- math425A-real-analysis
- csci670-advanced-analysis-of-algorithms
- ee503-probability
- csci699-computational-perspectives-on-ml
- csci675-convex-optimisation
- csci567-machine-learning
GENERAL:
- phy760-computational-methods-in-physics
OPTIMISATION:
- constrained-convex-optimisation
TABLE-TENNIS:
- phed-150A-table-tennis
VIDEORESOURCES:
- videoresources
