COURSES:
- ee546-mathematics-of-high-dimensional-data
- csci670-advanced-analysis-of-algorithms
- math574-applied-matrix-analysis
- csci675-convex-optimisation
GENERAL:
- phy760-computational-methods-in-physics
OPTIMISATION:
- phed-150A-table-tennis
- constrained-convex-optimisation
