Jacob Chanowski:
        - "It is important that students bring a certain rafamuffin, barefoot, irreverence to their studies; they are not here to worship what is known, but to question it"

C.A Helvétius:
        - The knowledge of certain principles easily compensates the lack of knowledge of certain facts [1759].

Teo Swee Ann: 
        - Excelling in everything at school is not the goal; doing well in subjects that interest them (his kids) is good enough

ToBeDetermined:
        - The only ways we know how to understand behaviour of a complex system are the following. By superposition of behaviour of its components. Or by abstracting the whole system as as blackbox and modelling its input output via a mapping (transfer function)
